sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  include:
    - python: 2.7
      env: TEST=slow
    - python: 3.5
      env: TEST=slow
services:
  - redis-server
install: >
  pip install -r requirements-dev.txt
script: >
  ./tests/travis/run.sh
